apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: test-app
    appstudio.openshift.io/component: testd2-componentos
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: testd2-componentos
  namespace: test
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: testd2-componentos
status:
  configuration:
    generatedName: ""
