apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testd23-componentos
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testd23-componentos
    app.kubernetes.io/part-of: test-app
  name: testd23-componentos
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: testd23-componentos
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: testd23-componentos
    spec:
      containers:
      - image: quay.io/psturc/test-images@sha256:31c5608ce6522ef1fe42f3484c02b43bf57375f8809f47bdfd0ef4f1186680da
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
